---
sudo: false
language: ruby
cache: bundler
env:
rvm:
- jruby-1.7.25
matrix:
  include:
  - rvm: jruby-9.1.10.0
    env: LOGSTASH_BRANCH=master
  fast_finish: true
install: true
script: ci/build.sh
jdk: oraclejdk8
